package com.mycompany.pia.gui;

import com.mycompany.pia.Video;
import com.mycompany.pia.db.VideoManager;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class AgregarVideo extends javax.swing.JFrame {
    private final ImageIcon iconError48 = new ImageIcon(new ImageIcon(
            getClass().getResource("/error_icon_48px.png")).getImage());
    private final ImageIcon iconCheck48 = new ImageIcon(new ImageIcon(
        getClass().getResource("/ok_icon_48px.png")).getImage());
    private JFileChooser fileChooser = new JFileChooser();
    private Path videoPath = null;
    private Path imagePath = null;
    
    public AgregarVideo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblArchivoVideo = new javax.swing.JLabel();
        lblArchivoImagen = new javax.swing.JLabel();
        txtArtista = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnArchivoVideo = new javax.swing.JButton();
        btnArchivoImagen = new javax.swing.JButton();
        btnAgergarVideo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        tabCatalogo = new javax.swing.JMenu();
        tabAgregarVideo = new javax.swing.JMenuItem();
        tabEditarVideo = new javax.swing.JMenuItem();
        tabVideos = new javax.swing.JMenu();
        tabLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(475, 430));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Añadir vídeo");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblArtista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArtista.setText("Artista:");

        lblArchivoVideo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArchivoVideo.setText("Ubicación del vídeo:");

        lblArchivoImagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArchivoImagen.setText("Ubicación de la imagen:");

        txtArtista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnArchivoVideo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnArchivoVideo.setText("Seleccionar archivo");
        btnArchivoVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoVideoActionPerformed(evt);
            }
        });

        btnArchivoImagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnArchivoImagen.setText("Seleccionar archivo");
        btnArchivoImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoImagenActionPerformed(evt);
            }
        });

        btnAgergarVideo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgergarVideo.setText("Añadir vídeo");
        btnAgergarVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgergarVideoActionPerformed(evt);
            }
        });

        tabCatalogo.setText("Catálogo");

        tabAgregarVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_icon.png"))); // NOI18N
        tabAgregarVideo.setText("Añadir vídeo");
        tabCatalogo.add(tabAgregarVideo);

        tabEditarVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_icon.png"))); // NOI18N
        tabEditarVideo.setText("Editar información de vídeos");
        tabCatalogo.add(tabEditarVideo);

        jMenuBar1.add(tabCatalogo);

        tabVideos.setText("Vídeos");
        jMenuBar1.add(tabVideos);

        tabLogout.setText("Cerrar sesión");
        tabLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabLogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(tabLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblArchivoVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblArchivoImagen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArtista)
                            .addComponent(txtNombre)
                            .addComponent(btnArchivoVideo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnArchivoImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnAgergarVideo)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArtista)
                    .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArchivoVideo)
                    .addComponent(btnArchivoVideo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArchivoImagen)
                    .addComponent(btnArchivoImagen))
                .addGap(32, 32, 32)
                .addComponent(btnAgergarVideo)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabLogoutActionPerformed
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_tabLogoutActionPerformed

    private void btnArchivoVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoVideoActionPerformed
        int returnVal = fileChooser.showOpenDialog(fileChooser);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            videoPath = Paths.get(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnArchivoVideoActionPerformed

    private void btnArchivoImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoImagenActionPerformed
        int returnVal = fileChooser.showOpenDialog(fileChooser);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            imagePath = Paths.get(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnArchivoImagenActionPerformed

    private void btnAgergarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgergarVideoActionPerformed
        String name = txtNombre.getText();
        String artist = txtArtista.getText();
        Video v = new Video(0, name, artist, videoPath, imagePath);
        VideoManager vm = new VideoManager();
        if(vm.crearVideo(v)) {    
            JOptionPane.showMessageDialog(rootPane,
                    "Vídeo agregado exitosamente.",
                    "Añadir vídeo", 1, iconCheck48);
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Error al agregar el vídeo.",
                    "Añadir vídeo", 0, iconError48);
        }
        this.dispose();
        new AgregarVideo().setVisible(true);
    }//GEN-LAST:event_btnAgergarVideoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgergarVideo;
    private javax.swing.JButton btnArchivoImagen;
    private javax.swing.JButton btnArchivoVideo;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblArchivoImagen;
    private javax.swing.JLabel lblArchivoVideo;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem tabAgregarVideo;
    private javax.swing.JMenu tabCatalogo;
    private javax.swing.JMenuItem tabEditarVideo;
    private javax.swing.JMenu tabLogout;
    private javax.swing.JMenu tabVideos;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
